## Introduction to Numpy

#### Numpy is a powerful python tool that is used to create and manipulate multi-dimensional array known as tensors or Matricces. Numpy is also an exceptional tool for Artificial Intelligence and it is nearly impossible to go into AI without knowning the fundamentals of Numpy.
#### Numpy provide users with Data manipulation tools such as large array manipulation (Matrices) and high level mathematical functions.

# PART 1

## How to Create a Numpy Array Part
#### there are several ways in which a Numpy Array can be formed, they are:

In [3]:
import numpy as np
list1 = [1,3,4,5]
arr1 = np.array(list1)
print(arr1)
type(arr1)

[1 3 4 5]


numpy.ndarray

In [4]:
#list1 + 2 --- this code will output an error because python list were not built to perform 
#vectorizedoperations, unlike arrays the function will output an array with every of its individual 
#item increased by 2"""

In [5]:
arr1 + 2

array([3, 5, 6, 7])

In [6]:
#once a list is created, you cant increase the size in order words a new one has to be created
# But such operation is possible with a list.
list2d = [[2,4,5], [3,5,2], [2,2,2]]
#A two Dimensional Array
arr2d = np.array(list2d)
print(arr2d)
print(type(arr2d))

[[2 4 5]
 [3 5 2]
 [2 2 2]]
<class 'numpy.ndarray'>


In [7]:
# The data type can also cbe specified as int, float,str, bool or object.
list2d_f = [[2,2,2], [3,3,3], [4,4,4]]
arr2d_f = np.array(list2d_f, dtype = "float")
print(arr2d_f)
print(type(arr2d_f))

[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]
<class 'numpy.ndarray'>


In [8]:
#Convert to int
arr2d_f.astype("int")

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [9]:
#Convert to str
arr2d_f.astype("int").astype("str")

array([['2', '2', '2'],
       ['3', '3', '3'],
       ['4', '4', '4']], dtype='<U11')

In [10]:
#Convert to bool
list2d_b = [5, 0, 10]
arr2d_b = np.array(list2d_b, dtype="bool" )
print(arr2d_b)

[ True False  True]


In [11]:
#or
arr2d_b.astype("bool")

array([ True, False,  True])

In [12]:
# Note: Every item in an array must contain same data type, but the list can take different dtypes.
# However to create an array with different items you can use the Object dtype.
list2d_o = [[2,3,4.5], ["ip",0,2]]
arr2d_o = np.array(list2d_o, dtype ="object")
print(arr2d_o)

[[2 3 4.5]
 ['ip' 0 2]]


In [13]:
# An array can always be converted back to a python list using the tolist() finction
arr2d_f.tolist()

[[2.0, 2.0, 2.0], [3.0, 3.0, 3.0], [4.0, 4.0, 4.0]]

In [14]:
# Differences Between python lists and arrays
#1 Array performs vectorized operations, while lists dont
#2 the size of an array cannot be increased, a new one has to be created
#3 An array occupies less space than an equivalent list of list
#4 Every has just one Data type except converted to an object

# PART 2

## Inspecting the Size and Shape of an array

#### most times we might be presented with arrays that wasnt built by us, and some of the very crucial parameters to watch out for are:

#### 1) check wether it is a 1 or 2 Dimensional array ( ""ndim"" is used )
#### 2) check how many items are present in each dimensions ( shape is used )
#### 3) check for the total number of items in the array ( ""size"" is used )
#### 4) check for the Data type of the array ( ""dtype"" is used )
#### 5) Getting first few samples of the item in the array ( indexing )

In [15]:
list2d = ([2,3,4,5], [2,4,6,8], [3,2,1,4])
arr2D = np.array(list2d, dtype= "int")
print(arr2D)

[[2 3 4 5]
 [2 4 6 8]
 [3 2 1 4]]


In [16]:
#ndim
print("Dimension :", arr2D.ndim)

Dimension : 2


In [17]:
#shape
print("shape :", arr2D.shape)

shape : (3, 4)


In [18]:
#size
print("Size :", arr2D.size)

Size : 12


In [19]:
#dtype
print("Data type :", arr2D.dtype)

Data type : int32


# PART 3

## How to extract specific items from an Array

In [20]:
#let us consider a 3 by 4 array Below
list2d = ([2,3,4,5], [2,4,6,8], [3,2,1,4])
arr2D = np.array(list2d, dtype= "int")
print(arr2D)

[[2 3 4 5]
 [2 4 6 8]
 [3 2 1 4]]


##### Note: Certain portion of an array can be indexed starting with Zero(0)

In [21]:
#Extract the first 2 rows and first 2 columns
arr2D[:2, :2]

array([[2, 3],
       [2, 4]])

In [22]:
#Doing the same thing for lists will output an error because, lists are indexed in a special way
#list2d[:2, :2] = error
list2d[1]

[2, 4, 6, 8]

In [23]:
#lastly, numpy arrays support boolean indexing
list2d = ([2,3,4,5], [2,4,6,8], [3,2,1,4])
arr2D = np.array(list2d, dtype= "int")
#Get boolean output by adding condition to each element
B = arr2D > 2
print(B)

[[False  True  True  True]
 [False  True  True  True]
 [ True False False  True]]


In [24]:
arr2D.size
#The code below will output the True values
arr2D[B]

array([3, 4, 5, 4, 6, 8, 3, 4])

In [25]:
C = arr2D > 4
print(C)

[[False False False  True]
 [False False  True  True]
 [False False False False]]


In [26]:
#The code below will output the False values
arr2D[C]

array([5, 6, 8])

In [28]:
arr2D.shape

(3, 4)

##### NOTE: Always note that when you index using the Code arr2D[x], where "x" is any variable name assigned to the numpy array,it only outputs the True or False statement that is greater in number.

# PART 4

## How to reverse the Rows and the whole Array

##### Note:Reversing an array works like what you would do in lists, but you have to reverse the axes one after the other.

In [91]:
list1_2d = [[2,3,4], [1,2,3], [2,2,3]]
arr2d_re = np.array(list1_2d, dtype = "int")
print(arr2d_re)

[[2 3 4]
 [1 2 3]
 [2 2 3]]


In [102]:
#Reverse only the row position by taking the one at the bottom to the top and 
#taking the one at the top to the bottom
arr2d_re[::-1, ]

array([[2, 2, 3],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
#Reverse both the row and column by taking the one at the left to the right and 
#taking the one at the right to the left.
arr2d_re[::-1, ::-1]

# PART 5

## How to represent missing values and infinite Values

#### To represent missing values, the following are used:
np.nan (not a number)
np.inf (infinite number)

In [95]:
import numpy as np
list4 = [[2,3,4,5], [1,2,3,4], [4,3,2,1]]
arr2d_new = np.array(list4)
arr2d_new.astype("float")

array([[2., 3., 4., 5.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [96]:
# arr2d[1,1] = 0
# arr2d[1,2] = 0
# print(arr2d)

In [97]:
# arr2d[1,1] = np.nan
# arr2d[1,2] = np.inf
# print(arr2d)

# PART 6

#### How to Compute Mean, Max, Min on ndarray

In [104]:
#Compute mean--The is the average of the overall matrix
mean1 = arr2d_new.mean()
print("The mean is", mean1)

The mean is 2.8333333333333335


In [105]:
#cmpute min--The is the smallest number
min1 = arr2d_new.min()
print("The min is: ", min1)

The min is:  1


In [106]:
#compute the max-- The max is the largest number of the matrice
max1 = arr2d_new.max()
print("The max is", max1)

The max is 5


##### The minimum  values can be gotten row wise and column wise. axis = 0 is for column, while axis = 1 is for row. Then the function ""np.amin()"" is used.

##### The np.amin(axis = 0) function outputs the minnimum number on all individual columns 
##### The np.amin(axis = 1) function outputs the minnimum number on all individual Rows

In [108]:
print("Column wise minimum :", np.amin(arr2d_new, axis = 0))

Column wise minimum : [1 2 2 1]


In [109]:
print("Row wise minimum :", np.amin(arr2d_new, axis = 1))

Row wise minimum : [2 1 1]


##### Note: you might want to do some computation row wise or column wise, the code code below can be used np.apply_over_axis, this will be discussed in later chapters.

In [110]:
#Cumulative Sum
np.cumsum(arr2d_new)

array([ 2,  5,  9, 14, 15, 17, 20, 24, 28, 31, 33, 34], dtype=int32)

# PART 7

#### How to create an array from an existing array

In [112]:
#call an Array
print(arr2d_new)

[[2 3 4 5]
 [1 2 3 4]
 [4 3 2 1]]


In [115]:
#assign part of array2d_new to a new variable
arr_part = arr2d_new[:2,:2]
print(arr_part)

[[2 3]
 [1 2]]


In [118]:
#Copy the part of that array into a new variable
arr_part1 = arr_part.copy()
print(arr_part1)

[[2 3]
 [1 2]]


# PART 8

#### Reshaping and flattening multidimensional Array

##### 1)when you reshape an array, the Arrangement of its item changes but the dimension remains the same

In [121]:
#use .reshape() function
arr2d_new.reshape(4, 3)

array([[2, 3, 4],
       [5, 1, 2],
       [3, 4, 4],
       [3, 2, 1]])

###### Note: when reshaping an array, the new shape must correspond to the number of items present e.g a 3 x 4 array has 12 elements, if you reshape it to 3 x 2, you will get an error. But you can reshape to 2 x 6

##### 2) when you flatten an array, it means you are changing the array from whatever dimension it was to a 1 dimensional array.

# PART 9

#### The Difference Between flatten() and ravel()

###### The major difference between flatten() and ravel() is that, ravel() is a reference to the parent array, i.e any changes made to the flattened array affects the parent array.

###### Although both of them perform same functions by being able to convert multidimensional array to a 1D array.

In [127]:
#using ravel function
arr_rav = arr2d_new.ravel()
print(arr_rav)

[2 3 4 5 1 2 3 4 4 3 2 1]


In [128]:
#using flatten function
arr2d_flat = arr2d_new.flatten()
print(arr2d_flat)

[2 3 4 5 1 2 3 4 4 3 2 1]


# PART 10

#### Creating Sequences, repetitions and random numbers in Numpy

###### The np.arange function comes in Handy, when trying to create a customized number sequence.

###### Note lower limit is always zero(0)

In [129]:
# lower limit is zero
print(np.arange(5))

[0 1 2 3 4]


In [130]:
# 0 to 9
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [131]:
# 0 to 9 with a step of 2
print(np.arange(0,10,2))

[0 2 4 6 8]


In [137]:
# 10 to 1, in a decreasing order
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


In [139]:
#Create exactly 10 numbers between 1 and 50
print(np.arange(1,50,5))

[ 1  6 11 16 21 26 31 36 41 46]


###### in order to prevent you from calculating the exact step that will give you exactly 10 numbers from 1 and 50, you can use the np.lonsapce() function. 

In [145]:
#start at 1 and stop at 50 
print(np.linspace(start=1, stop=50, num=10, dtype="int"))

[ 1  6 11 17 22 28 33 39 44 50]


###### note that in the above code, the dtype was explicitly typed, thereby making the numbers unequally spaced.

In [148]:
# similar to np.linspace(), there is np.logspace()
#start = 0, stop = 0
print(np.logspace(start=1, stop=50, num=10, base=10))
#using np.logspace() all number starts with base10(10^)

[1.00000000e+01 2.78255940e+06 7.74263683e+11 2.15443469e+17
 5.99484250e+22 1.66810054e+28 4.64158883e+33 1.29154967e+39
 3.59381366e+44 1.00000000e+50]


In [150]:
#limit the number of Decimals to 2
np.set_printoptions(precision=2)
print(np.logspace(start=1, stop=50, num=10, base=10))

[1.00e+01 2.78e+06 7.74e+11 2.15e+17 5.99e+22 1.67e+28 4.64e+33 1.29e+39
 3.59e+44 1.00e+50]


#### np.ones() and np.zeros() helps you ceate desired arrays where the items are either 1s or 0s.

In [158]:
#cretae an array and set all of its items to one(1)
onesArr = np.ones([2,2])
print(onesArr)

[[1. 1.]
 [1. 1.]]


In [160]:
#create an array and set all of its items to zero(0
zerosArr = np.zeros([2,2], dtype = "int" )
print(zerosArr)

[[0 0]
 [0 0]]


# PART 11

#### Creating repeating sequences

###### np.tile() will repeat a list or an array n times, while np.repeat() will repeat each item in the array n times.

In [161]:
Num = [1,2,3]
tiles = np.tile(Num, 3)
print(tiles)

[1 2 3 1 2 3 1 2 3]


In [163]:
Num = [1,2,3]
repeats = np.repeat(Num, 3)
print(repeats)

[1 1 1 2 2 2 3 3 3]


# Part 12

#### How to Generate Random numbers